#!/usr/bin/env bash
# ╔═══════════════════════════════════════════════════════════════════╗
# ║  Secure Proxy Manager — One-Click Installer                      ║
# ║  Usage: curl -fsSL https://raw.githubusercontent.com/            ║
# ║    fabriziosalmi/secure-proxy-manager/main/deploy/install.sh|bash║
# ╚═══════════════════════════════════════════════════════════════════╝
set -euo pipefail

REPO="https://github.com/fabriziosalmi/secure-proxy-manager.git"
INSTALL_DIR="/opt/secure-proxy-manager"
BRANCH="main"

C='\033[0;36m'; G='\033[0;32m'; R='\033[0;31m'; Y='\033[0;33m'; N='\033[0m'; B='\033[1m'

info()  { printf "${C}[INFO]${N} %s\n" "$1"; }
ok()    { printf "${G}[OK]${N}   %s\n" "$1"; }
warn()  { printf "${Y}[WARN]${N} %s\n" "$1"; }
fail()  { printf "${R}[FAIL]${N} %s\n" "$1"; exit 1; }

echo ""
printf "${C}╔═══════════════════════════════════════════════════════════╗${N}\n"
printf "${C}║${N}  ${B}Secure Proxy Manager — Installer${N}                       ${C}║${N}\n"
printf "${C}╚═══════════════════════════════════════════════════════════╝${N}\n"
echo ""

# ── Check root ────────────────────────────────────────────────────────
[ "$(id -u)" -eq 0 ] || fail "Please run as root: sudo bash install.sh"

# ── Check OS ──────────────────────────────────────────────────────────
info "Detecting OS..."
if [ -f /etc/os-release ]; then
    . /etc/os-release
    ok "OS: $PRETTY_NAME"
else
    warn "Could not detect OS — continuing anyway"
fi

# ── Install Docker if missing ─────────────────────────────────────────
if command -v docker &>/dev/null; then
    ok "Docker: $(docker --version | head -1)"
else
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
    ok "Docker installed"
fi

# ── Install Docker Compose plugin if missing ──────────────────────────
if docker compose version &>/dev/null; then
    ok "Docker Compose: $(docker compose version --short)"
else
    info "Installing Docker Compose plugin..."
    apt-get update -qq && apt-get install -y -qq docker-compose-plugin 2>/dev/null \
        || yum install -y docker-compose-plugin 2>/dev/null \
        || fail "Could not install Docker Compose plugin"
    ok "Docker Compose installed"
fi

# ── Install git if missing ────────────────────────────────────────────
if ! command -v git &>/dev/null; then
    info "Installing git..."
    apt-get install -y -qq git 2>/dev/null || yum install -y git 2>/dev/null
fi

# ── Clone or update repo ─────────────────────────────────────────────
if [ -d "$INSTALL_DIR" ]; then
    info "Updating existing installation..."
    cd "$INSTALL_DIR"
    git pull --ff-only origin "$BRANCH"
    ok "Updated to latest"
else
    info "Cloning repository..."
    git clone --depth 1 -b "$BRANCH" "$REPO" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
    ok "Cloned to $INSTALL_DIR"
fi

# ── Generate .env if missing ─────────────────────────────────────────
if [ ! -f .env ]; then
    info "Generating .env with random credentials..."
    ADMIN_USER="admin"
    ADMIN_PASS=$(openssl rand -hex 32)
    SECRET_KEY=$(openssl rand -hex 32)

    cat > .env <<EOF
# Auto-generated by install.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
BASIC_AUTH_USERNAME=${ADMIN_USER}
BASIC_AUTH_PASSWORD=${ADMIN_PASS}
SECRET_KEY=${SECRET_KEY}
CORS_ALLOWED_ORIGINS=https://localhost:8443
EOF

    ok "Credentials generated"
    echo ""
    printf "  ${B}Username:${N} ${ADMIN_USER}\n"
    printf "  ${B}Password:${N} ${ADMIN_PASS}\n"
    echo ""
    warn "Save these credentials! They won't be shown again."
    echo ""
else
    ok ".env already exists — keeping current credentials"
fi

# ── Build and start ──────────────────────────────────────────────────
info "Building containers (this may take 2-5 minutes on first run)..."
docker compose build --quiet 2>&1 | tail -3

info "Starting services..."
docker compose up -d

# ── Wait for healthy ─────────────────────────────────────────────────
info "Waiting for services to be healthy..."
for i in $(seq 1 30); do
    if curl -sk --max-time 2 https://localhost:8443/api/health 2>/dev/null | grep -q '"healthy"'; then
        break
    fi
    sleep 2
done

# ── Verify ───────────────────────────────────────────────────────────
if curl -sk --max-time 5 https://localhost:8443/api/health 2>/dev/null | grep -q '"healthy"'; then
    ok "All services healthy!"
else
    warn "Services still starting — check: docker compose ps"
fi

# ── Print access info ────────────────────────────────────────────────
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

echo ""
printf "${G}╔═══════════════════════════════════════════════════════════╗${N}\n"
printf "${G}║${N}  ${B}Installation Complete!${N}                                   ${G}║${N}\n"
printf "${G}╠═══════════════════════════════════════════════════════════╣${N}\n"
printf "${G}║${N}                                                           ${G}║${N}\n"
printf "${G}║${N}  Dashboard:  ${B}https://${LOCAL_IP}:8443${N}                   ${G}║${N}\n"
printf "${G}║${N}  Proxy:      ${B}${LOCAL_IP}:3128${N}                            ${G}║${N}\n"
printf "${G}║${N}  API Docs:   ${B}https://${LOCAL_IP}:8443/api/docs${N}           ${G}║${N}\n"
printf "${G}║${N}                                                           ${G}║${N}\n"
printf "${G}║${N}  Configure your devices to use proxy ${B}${LOCAL_IP}:3128${N}    ${G}║${N}\n"
printf "${G}║${N}  Accept the self-signed cert on first visit.              ${G}║${N}\n"
printf "${G}║${N}                                                           ${G}║${N}\n"
printf "${G}╚═══════════════════════════════════════════════════════════╝${N}\n"
echo ""
